# Generated by Django 3.2.3 on 2021-06-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210615_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infection',
            name='prefecture_id',
        ),
        migrations.AddField(
            model_name='infection',
            name='prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.prefecture'),
        ),
    ]
