# Generated by Django 3.2.3 on 2021-06-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_infection_date_string'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
